./new_task 1.
./new_task 2..
./new_task 3...
./new_task 4....
./new_task 5.....
./new_task 6......
./new_task 7.......
./new_task 8........
./new_task 9.........
./new_task 10..........
./new_task 11...........
./new_task 12............
./new_task 13...
./new_task 14....
./new_task 15.....
./new_task 16......

